apiVersion: v1
kind: Secret
metadata:
  name: zepto-db-secret
  namespace: zepto
type: Opaque
stringData:
  DB_HOST: zepto-mysql
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: "Root@123"
  DB_NAME: zepto_db
  MYSQL_ROOT_PASSWORD: "Root@123"
  JWT_SECRET: "mySuperSecretKey"