xname: Zepto CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/165290163749/locations/global/workloadIdentityPools/github-pool/providers/github-provider-v2'
          service_account: 'github-actions-zepto@zepto-ecommerce-app-506504.iam.gserviceaccount.com'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Verify Google Cloud authentication
        run: |
          gcloud auth list
          gcloud config set project zepto-ecommerce-app-506504
